---
# Site configuration
- include: basic_setup.yml
- include: build_servers.yml
- include: ganglia_collectors.yml
- include: ganglia_monitors.yml
- include: ganglia_web.yml
- include: zookeepers.yml
- include: qjournal_servers.yml
- include: hadoop_namenodes.yml
