---

- name: stop namenode services
  service: name={{ item }} state=stopped
  with_items:
    - hadoop-0.20-mapreduce-jobtrackerha
    - hadoop-hdfs-namenode

- name: start namenode services
  service: name={{ item }} state=started
  with_items:
    - hadoop-0.20-mapreduce-jobtrackerha
    - hadoop-hdfs-namenode

